version: '3'

services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_ENABLE_DEFAULT_SERVER: "False"
    ports:
      - "80:80"
    links:
      - db:postgres

  api8inf349:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_DEBUG: "True"
      FLASK_APP: "api8inf349"
      DB_HOST: "db"
      DB_USER: "user"
      DB_PASSWORD: "pass"
      DB_PORT: "5432"
      DB_NAME: "api8inf349"
      REDIS_HOST: cache

    command: >
      bash -c "flask init-db && flask run --host=0.0.0.0"

volumes:
  db_data:
