version: '3'

services:
  
  #conteneur postgresql
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
    volumes:
      - ./config_infos/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  
  #reddis version 5
  #cache:
    #image: reddis:5
    #restart: always
    #ports:
      #- "6379:6379"


  #conteneur pgadmin pas précisé dans les consignes 
  #mais qui m'a permis de vérifier les données sur la BD
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_ENABLE_DEFAULT_SERVER: "False"
    ports:
      - "80:80"
    links:
      - db:postgres

  #application web 
  api8inf349:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
