version: '3.9'

services:
  #cache:
    #image: redis:5
    #restart: always
    #ports:
     # - '6379:6379'
    #expose:
      #- '6379'
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DATABASE: 'api8inf349'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass' # spécifiez ici votre mot de passe
      POSTGRES_ROOT_PASSWORD: 'pass'     
    ports:
      - "5432:5432"
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql
volumes:
  my-db: